/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SheetIndexImport } from './routes/sheet/index'

// Create/Update Routes

const SheetIndexRoute = SheetIndexImport.update({
  id: '/sheet/',
  path: '/sheet/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sheet/': {
      id: '/sheet/'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/sheet': typeof SheetIndexRoute
}

export interface FileRoutesByTo {
  '/sheet': typeof SheetIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sheet/': typeof SheetIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sheet'
  fileRoutesByTo: FileRoutesByTo
  to: '/sheet'
  id: '__root__' | '/sheet/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SheetIndexRoute: typeof SheetIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SheetIndexRoute: SheetIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sheet/"
      ]
    },
    "/sheet/": {
      "filePath": "sheet/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
